services:
  openwrt-sdk:
    build:
      context: .
      dockerfile: Dockerfile
    image: mini-mwan-builder
    container_name: mini-mwan-builder
    volumes:
      # Mount mini-mwan package (daemon)
      - ./files:/builder/package/mini-mwan/files:ro
      - ./Makefile:/builder/package/mini-mwan/Makefile:ro
      # Mount luci-app-mini-mwan package (LuCI interface)
      - ./luci-app-mini-mwan/htdocs:/builder/package/luci-app-mini-mwan/htdocs:ro
      - ./luci-app-mini-mwan/root:/builder/package/luci-app-mini-mwan/root:ro
      - ./luci-app-mini-mwan/Makefile:/builder/package/luci-app-mini-mwan/Makefile:ro
      # Mount custom feeds configuration
      - ./feeds.conf:/builder/feeds.conf:ro
      # NOTE: .config is not mounted as a file because Docker creates directories for non-existent paths,
      # causing build failures when OpenWrt expects a file. Therefore, configuration will always remain
      # ephemeral, at least until the moment when I figure out how to work it around.
      # Mount output directory for built packages
      - ./bin:/builder/bin
      # Mount local OpenWRT repositories from host (create ~/openwrt-repos first)
      - ~/openwrt-repos:/openwrt-repos:ro
      # Use named volumes for build artifacts (faster than macOS filesystem)
      - openwrt-feeds:/builder/feeds
      - openwrt-dl:/builder/dl
    working_dir: /builder
    stdin_open: true
    tty: true

volumes:
  openwrt-feeds:
  openwrt-dl:
