services:
  openwrt-sdk:
    build:
      context: .
      dockerfile: Dockerfile
    image: mini-mwan-builder
    container_name: mini-mwan-builder
    volumes:
      # Mount sources readonly
      - ./mini-mwan:/builder/package/mini-mwan:ro
      - ./luci-app-mini-mwan:/builder/package/luci-app-mini-mwan:ro
      # Mount custom feeds configuration
      - ./feeds.conf:/builder/feeds.conf:ro
      # NOTE: there is no way to preserve .config between builds. Therefore, configuration will always remain
      # ephemeral, at least until the moment when I figure out how to work it around.
      # Mount output directory for built packages
      - ./bin:/builder/bin
      # Mount local OpenWRT repositories from host (create ~/openwrt-repos first)
      - ~/openwrt-repos:/openwrt-repos:rw
      # Use named volumes for build artifacts (faster than macOS filesystem)
      - openwrt-feeds:/builder/feeds
      - openwrt-dl:/builder/dl
    working_dir: /builder
    stdin_open: true
    tty: true

volumes:
  openwrt-feeds:
  openwrt-dl:
