services:
  openwrt-sdk:
    build:
      context: .
      dockerfile: Dockerfile
    image: mini-mwan-builder
    container_name: mini-mwan-builder
    volumes:
      # Mount the package source
      - ./:/builder/package/mini-mwan:ro
      # Mount output directory for built packages
      - ./bin:/builder/bin_output
    working_dir: /builder
    stdin_open: true
    tty: true
