services:
  openwrt-sdk:
    build:
      context: .
      dockerfile: Dockerfile
    image: mini-mwan-builder
    container_name: mini-mwan-builder
    volumes:
      # Mount package source files
      - ./files:/builder/package/mini-mwan/files:ro
      - ./htdocs:/builder/package/mini-mwan/htdocs:ro
      - ./root:/builder/package/mini-mwan/root:ro
      - ./Makefile:/builder/package/mini-mwan/Makefile:ro
      # Mount custom feeds configuration
      - ./feeds.conf:/builder/feeds.conf:ro
      # Mount output directory for built packages
      - ./bin:/builder/bin
      # Mount local OpenWRT repositories from host (create ~/openwrt-repos first)
      - ~/openwrt-repos:/openwrt-repos:ro
      # Use named volumes for build artifacts (faster than macOS filesystem)
      - openwrt-feeds:/builder/feeds
      - openwrt-dl:/builder/dl
    working_dir: /builder
    stdin_open: true
    tty: true

volumes:
  openwrt-feeds:
  openwrt-dl:
