include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Mini-MWAN
LUCI_DEPENDS:=+mini-mwan

PKG_MAINTAINER:=Alex Schwartzman <openwrt@schwartzman.uk>
PKG_LICENSE:=GPL-2.0
PKG_VERSION:=1.0.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
