include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Mini-MWAN
LUCI_DEPENDS:=+mini-mwan

PKG_MAINTAINER:=Your Name <your.email@example.com>
PKG_LICENSE:=GPL-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
